# Generated by Django 3.2.8 on 2021-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='image',
            field=models.ImageField(default=None, upload_to='chocolates'),
        ),
    ]
