# Generated by Django 3.2.8 on 2021-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0003_auto_20211024_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
