# Generated by Django 3.2.8 on 2021-10-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0005_alter_chocolate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='keyword',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
