# Generated by Django 3.2.8 on 2021-10-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0007_alter_chocolate_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
    ]
