# Generated by Django 3.2.8 on 2021-10-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0008_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Queries'},
        ),
        migrations.AddField(
            model_name='chocolate',
            name='amazon_url',
            field=models.CharField(default='https://www.instagram.com/e_trunk_/', max_length=50),
        ),
    ]
